authentication/urls.py
from django.urls import path,include
from . import views
 
from django.conf import settings
from django.conf.urls.static import static
 
app_name = 'authentication'
urlpatterns = [
    path('signup', views.signup , name = "signup"),
    path('signin', views.signin , name = "signin"),
    path('signout', views.signout , name = "signout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path,include
from . import views

from django.conf import settings
from django.conf.urls.static import static


app_name = 'homepage'
urlpatterns = [
    path('', views.home , name = "home"),
    path('camera/<str:mode>', views.camera , name = "camera"),
    
    path('register_check', views.register_check , name = "register_check"),

    path('tester', views.tester , name = "tester"),
    path('remove_barcode', views.remove_barcode , name = "remove_barcode"),
    path('remove_hyoushi', views.remove_hyoushi , name = "remove_hyoushi"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labelreader/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('homepage.urls') ),
    path('image_processing/', include('image_processing.urls') ),
    path('management/', include('management.urls') ),
]

management/urls.py
from django.urls import path,include
from . import views

from django.conf import settings
from django.conf.urls.static import static


app_name = 'management'
urlpatterns = [
    path('', views.search , name = "search"),
    path('search_form_action', views.search_form_action , name = "search_form_action"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} base {%endblock%}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    
    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">
</head>
<body>

    <header class="nav-header" id="top" >
        <div class="nav-sitetitle">
            <a href="#" style=" margin: 45px 0 15px 35%;">
                <label class="nav-label">LABEL READER</label>
            </a>
        </div>
    </header>

    <div class="container">
        {% block body %}
        
        {% endblock %}
    
    </div>

    <footer class="page-footer">
        <div class="footer-container">
            <p class="copyright">© Sic All rights reserved.</p>
        </div>
    </footer>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
</body>
</html>

templates/base_with_nav.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <title>{% block title %} base {%endblock%}</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    
    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">
</head>
<body>
    <div class="top-nav">
        <header class="nav-header-2" id="top" >
            <div class="nav-sitetitle">
                <a href="#" style=" margin: 45px 0 15px 20%;">
                    <label class="nav-label">LABEL READER</label>
                </a>
            </div>
        </header>

        <div class="navbar">
            <a href="#" class="active" style="font-family: 'Noto Sans JP', sans-serif;" >ホーム</a>
            <a href="#" style="font-family: 'Noto Sans JP', sans-serif;" >使い方</a>
            <a href="{% url 'management:search' %}" style="font-family: 'Noto Sans JP', sans-serif;" >管理</a>
            {% if request.user.is_authenticated %}
                <a href="#" style="font-family: 'Noto Sans JP', sans-serif;" >{{request.user.username}}</a>
            {% else %}
                <a href="#" style="font-family: 'Noto Sans JP', sans-serif;" >新規アカウント</a>
            {% endif %}
            {% if request.user.is_authenticated %}
                <a href="{% url 'authentication:signout' %}" style="font-family: 'Noto Sans JP', sans-serif;" >ログアウト</a>
            {% else %}
                <a href="#" style="font-family: 'Noto Sans JP', sans-serif;" >ログイン</a>
            {% endif %}
        </div>
    </div>           
        
    <div class="end-nav"></div>

    <div class="container main-body">
        <h5 class="session-info">職員ID : {{request.user.username}}</h5>
        <h5 class="session-info">日付 : <span id="currentDate"></span><input type="text" id="tourokubi" name="tourokubi" value="" style="display: none;"></h5>
        <hr>

        {% block body %}
        
        {% endblock %}
        
    </div>
    <div class="footer-start" id="footer-start"></div>
    <footer id="footer" class="page-footer">
        <div class="footer-container">
            <p class="copyright">© Sic All rights reserved.</p>
        </div>
    </footer>
    
    <div id="content-top1" class="top"style="position: relative;">
        <a href="#top" id="topBtn" style="position: fixed;bottom: 10px;right: 10px; width: 64px; height: 64px;line-height: 64px;text-align: center;
        background-color: #333;color: rgb(255, 255, 255);">TOP</a>
    </div>
    <div id="content-top2" class="top"style="position: relative;">
        <a href="#top" id="onseiBtn" style="position: fixed;bottom: 80px; right: 10px;width: 64px;height: 64px;line-height: 64px;text-align: center;
        background-color: rgb(0, 102, 255); color: rgb(255, 255, 255);">音声</a>
    </div>
    
    <script>
        window.onload = function(){
            var dateObj = new Date();
            var y = dateObj.getFullYear();
            var m = dateObj.getMonth() + 1;
            var d = dateObj.getDate();
            var yb = "日月火水木金土".charAt(dateObj.getDay());
            document.getElementById("currentDate").innerHTML = y+"年"+m+"月"+d+"日("+yb+")";
            document.getElementById("tourokubi").value = y+"/"+m+"/"+d;
        }


        /* SHOW TOP button at end of page */

        $(document).ready( function() {
            $("#content-top1").hide(); //hide your div initially
            $("#content-top2").hide(); //hide your div initially
            var topOfOthDiv = $("#footer-start").offset().top;
            
            $(window).scroll(function() {
                if($(window).scrollTop() >= topOfOthDiv - 90) { //scrolled past the other div?
                    $("#content-top1").show() //reached the desired point -- show div
                    $("#content-top2").show(); //reached the desired point -- show div
                }
                else{
                    $("#content-top1").hide(); //reached the desired point -- show div
                    $("#content-top2").hide(); //reached the desired point -- show div
                }
            });
        });

    </script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
</body>
</html>

templates/camera.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    
    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">
</head>
<body>
<div class="full-camera-page-div">

    <form action="{% url 'homepage:tester' %}" method="POST" class="full-camera-form" enctype="multipart/form-data" onSubmit="return double()">
        <div class="full-camera-form-div">

        <input type="hidden" name="camera_mode" value={{camera_mode}}>

        <!--<img class="image" src="./static/css/css_img/SmartPhon1.png" style="width: 55%; height: 8%; margin: 5% 22.5% 0px 22.5%;"><br>-->
        <video id="camera" autoplay playsinline class="full-camera-video-frame"></video>
        <!--シャッター-->
        <div id="indicator-target" class="indicator" style="height: 100%;">

        <div class="row">

            <div class="col-lg-8">

                <input type=submit value=""id='indicator' class="submit_btn" formaction="{% url 'homepage:tester' %}" onclick="take_picture(),counter(),sound()" 
                style="margin: 0px 75%; margin-top: -20px  ;background-color: white; background-size:contain; width: 200px; height: 50px; max-width: 50px; max-height: 50px; border-radius:30px; 
                padding-top: 0; border: 2px solid #9c9c9c;">
            
        </div>

            <div class="col-lg-3">
                <button class="btn btn-danger" style="margin-top: -13px; width: 150px;" onclick="history.back()">キャンセルs</button>
            </div>
        
        </div>

        <canvas id="canvas" width="0px" height="0px" style="display: none;"></canvas>
        
        </div>
        
        <audio id="demo_sound" preload="auto">
            <source src="../static/audio/カメラのシャッター2.mp3" type="audio/mp3">
        </audio>

    <script>
        function sound() {
            var se = document.getElementById('demo_sound');
            se.play();
        }

        //カメラ用意
        var video = document.getElementById('camera');
        const se = document.querySelector('#se');
        
        // カメラ設定
        const constraints = {
        audio: false,
        video: {
            width: 5000,
            height: 800,
            facingMode: "environment"   // フロントカメラを利用する⇒user
        }
        };

        //カメラを<video>と同期
        navigator.mediaDevices.getUserMedia(constraints)
        .then( (stream) => {
        video.srcObject = stream;
        video.onloadedmetadata = (e) => {
            video.play();  
        };
        })
        .catch( (err) => {
        console.log(err.name + ": " + err.message);
        });
        
        //カウンターファンクション
        var kaisu = 0;
        function counter() {
            var count = document.getElementById('count');
            var c = parseInt(count.value)
            if(c == 1){
            //Annnoyの類似画像出力の際にともに出力した撮影した写真を消す
            var hyoushi_img = document.getElementById('hyoushi_img');
            hyoushi_img.style.display ="none";
            count.value = ++c;
            }else{
            count.value = ++c;
            }
        }
            //撮影ファンクション
        function take_picture() {
            //videoのstreamをcanvasに書き出す方法
            var canvas = document.getElementById('canvas');
            var ctx = canvas.getContext('2d');
            //videoの縦幅横幅を取得
            var w = video.offsetWidth;
            var h = video.offsetHeight;
            canvas.setAttribute("width", w);
            canvas.setAttribute("height", h);
            ctx.drawImage(video, 0, 0, w, h);
    
            //canvasをimgに書き出し
            var img = document.getElementById('img_data');
            img.value = canvas.toDataURL('image/jpg');

            var w = 180;
            var h = 180;
            canvas.setAttribute("width", w);
            canvas.setAttribute("height", h);
            ctx.drawImage(video, 0, 0, w, h);

        }
</script>
<!--  -->
        <div style="margin-top: 0px;">
                <input type="text" id="count" name="count" value={{cameraclick}} style="display: none;" >
                <input type="text" id="img_data" name=img_data value=""  style="display: none;">
            </div>
        </div>

                {% if barcord %}
                <input type="text" id="barcord" name="barcord" value={{barcord}} style="display: none;" >
                {% endif %}
    </form>
</body>
</html>