homepage/urls.py
from django.urls import path,include
from . import views

from django.conf import settings
from django.conf.urls.static import static


app_name = 'homepage'
urlpatterns = [
    path('', views.home , name = "home"),
    path('camera/<str:mode>', views.camera , name = "camera"),
    
    path('register_check', views.register_check , name = "register_check"),

    path('tester', views.tester , name = "tester"),
    path('remove_barcode', views.remove_barcode , name = "remove_barcode"),
    path('remove_hyoushi', views.remove_hyoushi , name = "remove_hyoushi"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labelreader/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('homepage.urls') ),
    path('image_processing/', include('image_processing.urls') ),
    path('management/', include('management.urls') ),
]

homepage/forms.py
from django import forms

class productinstanceform(forms.Form):
    camera_mode = forms.CharField(max_length=100)
    count = forms.CharField(max_length=100)

homepage/views.py
from email.mime import image
from multiprocessing import context
from venv import create
from django.shortcuts import redirect, render


from django.views.decorators.csrf import csrf_exempt
from numpy import save
from core.models import product

from .forms import productinstanceform

import os
import base64
from django.core.files.base import ContentFile

#DEPENDENCIES
import cv2

#Support functions
from image_processing.views import barcode_comparison,image_similarity



# Create your views here.
def home(request):
    if request.user.is_authenticated:
        curruser = request.user

        product_instance,created = product.objects.get_or_create(
            created_by = request.user,
            status = 0,
            
            defaults={
                'barcode_image' : None,
                'cover_image' : None,
                'label_image' : None,
                'kensa_bango' : None,
                'kensa_id' : None,
                'shouhinmei' : None,
            }
        )

        print('instance created is ', product_instance , created)

        return render(request,'landing/homepage.html',{'curr_user' : curruser, 'productinstance' : product_instance})
    else:
        return redirect('authentication:signin')

def camera(request,mode):
    if request.user.is_authenticated:
        curruser = request.user

        productinstance = product.objects.get(created_by = request.user , status = 0)

        context = {
            'cameraclick' : 1 ,
            'FoodCheck' : 1 ,
            'userid' : curruser.id,
            'result_img1' : 'TEST/IMAGE/PATH',
            'camera_mode' : mode,
            'productinstance' : productinstance
        }
        
        return render(request,'camera.html', context)
    
    else:

        return redirect('authentication:signin')

@csrf_exempt
def tester(request):

    if request.method == "POST":

        current_product_instance = product.objects.get(created_by = request.user, status = 0)

        form = productinstanceform(request.POST, request.FILES)

        if form.is_valid():
            camera_mode = form.cleaned_data.get("camera_mode")
            count = form.cleaned_data.get("count")
            img_base64 = request.POST.get('img_data')
            
            if camera_mode == "barcode":
                
                format, imgstr = img_base64.split(';base64,') 
                ext = format.split('/')[-1] 

                data = ContentFile(base64.b64decode(imgstr))  
                file_name = str(current_product_instance.id) + str(request.user.username) + str('_barcode.') + ext

                current_product_instance.barcode_image.save(file_name,data, save=True)

            else:

                format, imgstr = img_base64.split(';base64,') 
                ext = format.split('/')[-1] 

                data = ContentFile(base64.b64decode(imgstr))  
                file_name = str(current_product_instance.id) + str(request.user.username) + str('_hyoushi.') + ext

                current_product_instance.cover_image.save(file_name,data, save=True)

            current_product_instance.save()

        else:
            print(form.errors)
            print('Form is not valid')

        return redirect('homepage:home')
    
    else:
        print('GET REQUEST')
        return redirect('homepage:home')


def remove_barcode(request):

    print('remove barcode')
    current_product_instance = product.objects.get(created_by = request.user, status = 0)
    current_product_instance.barcode_image = None
    current_product_instance.save()

    return redirect('homepage:home')


def remove_hyoushi(request):

    print('remove hyoushi')
    current_product_instance = product.objects.get(created_by = request.user, status = 0)
    current_product_instance.cover_image = None
    current_product_instance.save()

    return redirect('homepage:home')


def register_check(request):

    print('check based on uploadded barcode and cover before register')

    
    try:
        product_instance = product.objects.get(created_by = request.user, status = 0, image_similarity_checked = 0)

    except:
        context = {
            error_message : "エラー　：　※ページエラー、 また試してみてください !"
        }
        return render(request, 'landing/homepage.html', context)

    
    #Since product image is hissu koumoku
    
    if not product_instance.cover_image:

        product_instance,created = product.objects.get_or_create(
            created_by = request.user,
            status = 0,
            
            defaults={
                'barcode_image' : None,
                'cover_image' : None,
                'label_image' : None,
                'kensa_bango' : None,
                'kensa_id' : None,
                'shouhinmei' : None,
            }
        )

        error_message = "エラー　：　※　表紙撮影を入力してください"

        context = {
            'productinstance' : product_instance,
            'error_message' : error_message
        }

        return render(request, 'landing/homepage.html', context)

    
    if not product_instance.barcode_image:
        
        related_images =  image_similarity(product_instance)

        print('related_images SCANNED IS ' , related_images)

        context = {
            'productinstance' : product_instance,
            'related_images' : related_images
        }

        return render(request, 'landing/homepage.html', context)


    elif product_instance.barcode_image:
        #No Annoy processing since QR code check is 100% declarative
        print('ONLY VERIFYING BARCODE')
        barcode_scanned = barcode_comparison(product_instance)

        print('BARCODE SCANNED IS ' , barcode_scanned)

        #if it matches with any entries with same barcode values in db

        if barcode_scanned == 'バーコードを撮影してください。':
            error_message = "エラー　：　※　バーコードエラー！バーコードを撮影してください。"

            context = {
                'productinstance' : product_instance,
                'error_message' : error_message
            }

            return render(request, 'landing/homepage.html', context)
        
        else:

            related_barcodes = product.objects.all().filter(qr_bango = barcode_scanned)

            context = {
                'productinstance' : product_instance,
                'related_barcodes' : related_barcodes
            }
            return render(request, 'landing/homepage.html', context)

templates/landing/homepage.html
<!DOCTYPE html>
{% extends "base_with_nav.html" %}
{% load static %}

{% block title %}

Homepage

{% endblock %}

{% block body %}

<link href="http://code.htmlhifive.com/h5.css" rel="stylesheet" >

<script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>

<script src="http://www.htmlhifive.com/ja/res/lib/bootstrap3/js/bootstrap.min.js"></script>
<script src="http://code.htmlhifive.com/ejs-h5mod.js"></script>
<script src="http://code.htmlhifive.com/h5.dev.js"></script>

<script src="{% static 'js/progress.js' %}"> </script>

<script src="{% static 'js/indicator-all-controller.js' %}"></script>

{% if error_message %}

<div class="error_message">
  <p class="error_message_text"> {{error_message}} </p>
</div>

{% endif %}

<div class="row-lg-12 homepage-content">
    
    <div class="col-lg-5">

      <div class="jumbotron homepage-jumbo">

        <h4 class="shooting-guide-title2">撮影した写真</h4>
        <hr>

        <div class="barcode_preview">
          
          <h5 class="shooting-guide-title2-header">バーコード撮影:</h5><br>
            
          {% if productinstance.barcode_image %}
          
            <div>
              <img src="{{productinstance.barcode_image.url}}" class="barcode_upload_preview" alt="broken barcode">
              <a href=" {% url 'homepage:remove_barcode' %} "> <button class="btn btn-danger barcode_upload_delete"> 削除 </button> </a>
            </div>
          
          {% else %}
          
            <div class="row">
              
              <div class="col-lg-6">
                <p class="shooting-guide-title2-content"> イメージなし </p>
              </div>
              
              <div class="col-lg-6">
              
                <a href=" {% url 'homepage:camera' 'barcode' %} "> <button class="btn btn-primary barcode-cam-button"> <i class="fas fa-camera"></i> バーコードカメラ </button> </a>
                <input type="file" name="barcode-image-input" id="barcode-file">
              
              </div>
            
            </div>
            
            
          {% endif %}
        
        </div>

        <br><hr><br>

        <div class="Hyoshi_satsuei_preview">
          
          <h5 class="shooting-guide-title2-header">表紙撮影:</h5><br>
          
          {% if productinstance.cover_image %}

          <div>
            <img src="{{productinstance.cover_image.url}}" class="hyoushi_upload_preview" alt="broken cover image">
            <a href="{% url 'homepage:remove_hyoushi' %}"> <button class="btn btn-danger hyoushi_upload_delete"> 削除 </button> </a>
          </div>

          {% else %}

            <div class="row">
                
              <div class="col-lg-6">
                <p class="shooting-guide-title2-content"> イメージなし </p>
              </div>
              
              <div class="col-lg-6">
              
                <a href="{% url 'homepage:camera' 'hyoshi' %}"> <button class="btn btn-primary hyosat-cam-button"> <i class="fas fa-camera"></i> 表紙撮影カメラ </button> </a>
                <input type="file" name="hyosat-file-input" id="hyosat-file">

              </div>
            
            </div>

          {% endif %}
        </div>
      
      </div>

    </div>

    <div class="col-lg-5">

      <div class="warning-text-div">
        <h4 class="shooting-guide-title1 title-text">撮影案内</h4>

        <hr>
        
        {% if productinstance.barcode_image %}

          <p class="success-text">※バーコード写真 <i class="fa fa-check" aria-hidden="true"></i> </p>
        
        {% else %}
          
          <p class="warning-text">※バーコード写真を撮影してください </p>
        
        {% endif %}
  
        {% if productinstance.cover_image %}
          
          <p class="success-text">※表紙撮影写真 <i class="fa fa-check" aria-hidden="true"></i></p>

        {% else %}
        
          <p class="danger-text">※表紙撮影写真を撮影してください（必須）</p>
        
        {% endif %}

        {% if related_images %}
          <div id="indicator-target" class="indicator">
            <a href="#" ><button id='indicator' class="home-skip-button">登録</button></a>
          </div>
        {% else %}
          <div id="indicator-target" class="indicator">
            <a href="{% url 'homepage:register_check' %}"><button id='indicator' class="home-skip-button">画像チェック</button></a>
          </div>
        {% endif %}
      
      </div>
      
      <hr style="margin-top: 5%;">

      <div class="similar-barcodes-block" style="margin-top: 10%;">
        <h4 class="title-text"> 似ているバーコード :</h4>

        {% if related_barcodes %}
          
          <div class="row">

            <div class="col-lg-12">

              {% if related_barcodes.0.barcode_image.url %}

                <img class="similar_barcodes" src="{{related_barcodes.0.barcode_image.url}}" alt="broken">

              {% else %}

                <div class="empty_similar_barcodes">
                  
                </div>
              
              {% endif %}

            </div>
            
          </div>
        {% else %}

          <p class="no-barcode-warning-text">バーコードなし</p>

        {% endif %}
      </div>

      <hr style="margin-top: 15%;">

      <div class="similar-images-block" style="margin-top: 10%;">
        <h4 class="title-text"> 似ている画像 :</h4>

        {% if related_images %}
          
          <div class="row">

            <div class="col-lg-4">
              <img class="similar_images" src="{{related_images.0.cover_image.url}}" alt="broken">
            </div>

            <div class="col-lg-4">
              {% if related_images.1.cover_image.url %}
                <img class="similar_images" src="{{related_images.1.cover_image.url}}" alt="broken">
              {% else %}
                <div class="empty_similar_image">
                </div>
              {% endif %}
            </div>

            <div class="col-lg-4">
              {% if related_images.2.cover_image.url %}
                <img  class="similar_images" src="{{related_images.2.cover_image.url}}" alt="broken">
              {% else %}
                <div class="empty_similar_image">
                </div>
              {% endif %}
            </div>
            
          </div>
        {% else %}

          <p class="no-image-warning-text">イメージなし</p>

        {% endif %}
      </div>

    </div>

</div>

{% endblock %}